text_offset = 0x0
text_size = 0xE20
text_address = 0x04001080
rom_file_path = "build/us_n64/rsp/audio.bin"
output_file_path = "rsp/aspMain.cpp"
output_function_name = "aspMain"
extra_indirect_branch_targets = [0x1118, 0x1470, 0x11dc, 0x1b38, 0x1214, 0x187c, 0x1254, 0x12d0, 0x12ec, 0x1328, 0x140c, 0x1294, 0x1e24, 0x138c, 0x170c, 0x144c]
